server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Semua route diarahkan ke index.html (untuk React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
