server {
    listen 80;

    # Device Service Frontend
    location /device/ {
        proxy_pass http://device-frontend:8081/device/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Tambahkan entry berikut saat wps-frontend & pps-frontend siap:
    # location /wps/ {
    #     proxy_pass http://wps-frontend:8082/wps/;
    #     proxy_http_version 1.1;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }

    # location /pps/ {
    #     proxy_pass http://pps-frontend:8083/pps/;
    #     proxy_http_version 1.1;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }
}
